name: macOS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v2
    - name: Setting the Environment Up.
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: source setup.sh "Alone215" "Alone215" "$NGROK_AUTH_TOKEN"
    - name: Setup tmate Session
      uses: mxschmitt/action-tmate@v2
